name: Python package
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Run tests
        run: PYTHONPATH=src poetry run pytest
      - name: Lint
        run: PYTHONPATH=src poetry run pylint src
